### ISSUE TITLE
Model of issue text to status

### ISSUE THREAD

**Issue by joseribasfernandes** [ivanduka/human-robot#13]

**Comment by nipun-goyal** [comment]
In-progress. Reading about the BERT technique to understand how to apply it on the status_text column data that we have

**Comment by joseribasfernandes** [comment]
Closing status modelling after conversation with Patti and Lucas on October 5th. According to Lucas and Patti status column in EIL tables is not used by environmental specialists, it is multidimensional (multiple VECs per issue), current labels Resolved/Unresolved/Monitor mean different things for different VECs, for example for vegetation, which takes more than 5 years to be restored, On Track is a better description, and often to assess if a field activity is needed, specialists need to check text.
