### ISSUE TITLE
Send maps layers to Alex

### ISSUE THREAD

**Issue by joseribasfernandes** [ivanduka/human-robot#18]
Email to Alex, layers:
-VEC
-Company
-Project
-Land use
-Consultant
-Issue > mock layer
-Year
-all the rows
-(maybe later PDF)

Deployed in a place where it is accessible by team of environmental specialists. 

Sometime next week or in next two weeks.

How to handle changes?

**Comment by nipun-goyal** [comment]
mail sent! awaiting Alex's response!
