### ISSUE TITLE
Question to filter database? How to filter the location on a map?

### ISSUE THREAD

**Issue by joseribasfernandes** [ivanduka/human-robot#22]

**Comment by nipun-goyal** [comment]
Spoke with Alex! On database side it is okay to store locations as string without the need of breaking them into different columns as someone filtering the location database by just section (i.e. SE, SW, NE, NW) doesn't really makes sense. Alex will check with George if we can have location drop down list in map interface to enable filtering issues by location

**Comment by nipun-goyal** [comment]
George created NTS and DLS layers on the map interface already! Will check with Alex how can we have drop-down list for locations
