### ISSUE TITLE
Data Dictionary for database

### ISSUE THREAD

**Issue by joseribasfernandes** [ivanduka/human-robot#23]
Check Curtis

**Comment by nipun-goyal** [comment]
two options suggested! Ze to take a call which option should we go for (I personally favor the first one). We might not have time right now and data dictionary can be created once the first phase of the project is completed

**Comment by joseribasfernandes** [comment]
option 1: prepare a word document with the history and version modification of the dataset (more comprehensive)
option 2: add a column in comments section of database (easy to implement and simple because it is in a single place, but less comprehensive)

Nipun and Ze have decided to go for option 1, because it is more comprehensive. We will take care of this after the Steering Committee.
